pic = makePicture(pickAFile())
show(pic)
pixels = getPixels(pic)
setColor(pixels[0], black)
setColor(pixels[1], black)
setColor(pixels[2], black)
setColor(pixels[3], black)
setColor(pixels[4], black)
setColor(pixels[5], black)
setColor(pixels[6], black)
setColor(pixels[7], black)
setColor(pixels[8], black)
setColor(pixels[9], black)
repaint(pic)